[package]
name = "griffin"
version = "0.1.0"
authors = ["Lahiru Himesh <lahiru.lahirumadusanka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_derive = "1.0"
config = "0.9"
